#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    dnsimple-dyndns
    ~~~~~~~~~~~~~~~

    :copyright: (c) 2013 by Rafael Goncalves Martins
    :license: BSD, see LICENSE for more details.
"""

import sys
from dnsimple_dyndns import main

sys.exit(main())
